### PR TITLE
Added boolean type

### PR DESCRIPTION
**Pull request by dawkaa**
I added boolean type with tests.

### CODE REVIEW

**Comment by npotier** [comment]
Hello @dawkaa thank you for your PR.

I think we should also edit the method `castValue()` method located in `src/Transformer/DoctrineToTypesenseTransformer.php` in order to cast the object value to a boolean.

**Comment by dawkaa** [comment]
> Hello @dawkaa thank you for your PR.
> 
> I think we should also edit the method `castValue()` method located in `src/Transformer/DoctrineToTypesenseTransformer.php` in order to cast the object value to a boolean.

Hello, sure i fixed it.

**Comment by dawkaa** [comment]
@npotier

**Comment by npotier** [comment]
Thanks @dawkaa this feature has been added.

it is available in version `0.7.3` of the bundle

**Pull request merged**
