### PR TITLE
Draft: use the php typesense client

### PR DESCRIPTION
**Pull request by etienneleba**
[x] use php typesense client
[ ] update README 
[ ] update composer.json php version to 7.4
[ ] add 7.4 node on travis

### CODE REVIEW

**Comment by etienneleba** [comment]
@npotier It's working great, tell me what you think about the implementation

**Comment by etienneleba** [comment]
We could use dependency inversion to not depend on the php typesense library, but most of the time bundle depends on the php library

**Comment by pierre-H** [comment]
Hello !

Any news about that ?

**Comment by npotier** [comment]
Closing this PR in favor of #25

**Pull request closed without merging**
