### PR TITLE
Allow to call a method from a service instead of a getter

### PR DESCRIPTION
**Pull request by lucasferraro**
Hi, 

In our project for some entity fields we need to use services to get the value instead of just a getter.

In order to be able to do that, we thought of this functionality with which now we can configure a field to obtain its value from a service. An example configuration would be:
```
fields:
    conver_image_url:
        entity_attribute: 'AppBundle\Typesense\Converter\BookConverter::getCoverImageURL'
        name: cover_image_url
        type: string
```

And then the class would accept the entity as parameter and could has some service injected to get the value:
```
class BookConverter 
{
    public function __construct(SomeExtraService $extraService)
    {
        $this->extraService = $extraService;
    }

    public function getCoverImageURL($book): string
    {
        // Use injected service to generate image URL
    }
}
```

### CODE REVIEW

**Comment by lucasferraro** [comment]
I've changed this PR to `Draft` because when I try to run our project using my fork I'm getting this error for import command:

```
18:40:24 CRITICAL  [console] Error thrown while running command "typesense:import". Message: "Call to undefined method Doctrine\DBAL\Configuration::setMiddlewares()" ["exception" => Error { …},"command" => "typesense:import","message" => "Call to undefined method Doctrine\DBAL\Configuration::setMiddlewares()"] ["token" => null]

In ImportCommand.php line 70:
                                                                               
  Attempted to call an undefined method named "setMiddlewares" of class "Doct  
  rine\DBAL\Configuration".
```

I saw that the error comes from a change that is in the `master` branch of the project introduced in [this commit](https://github.com/acseo/TypesenseBundle/commit/00a67b2c6b0a929ef24302e60c5ab5bcb0edcf87):
https://github.com/acseo/TypesenseBundle/blob/9cc51e6274f60237a40e28c0df7d56d4aa8dbe87/src/Command/ImportCommand.php#L70-L72
I'm trying to figure out how to fix this on our side, in the meantime any help is welcome :)

**Comment by lucasferraro** [comment]
> I've changed this PR to `Draft` because when I try to run our project using my fork I'm getting this error for import command:
> 
> ```
> 18:40:24 CRITICAL  [console] Error thrown while running command "typesense:import". Message: "Call to undefined method Doctrine\DBAL\Configuration::setMiddlewares()" ["exception" => Error { …},"command" => "typesense:import","message" => "Call to undefined method Doctrine\DBAL\Configuration::setMiddlewares()"] ["token" => null]
> 
> In ImportCommand.php line 70:
>                                                                                
>   Attempted to call an undefined method named "setMiddlewares" of class "Doct  
>   rine\DBAL\Configuration".
> ```
> 
> I saw that the error comes from a change that is in the `master` branch of the project introduced in [this commit](https://github.com/acseo/TypesenseBundle/commit/00a67b2c6b0a929ef24302e60c5ab5bcb0edcf87):
> 
> https://github.com/acseo/TypesenseBundle/blob/9cc51e6274f60237a40e28c0df7d56d4aa8dbe87/src/Command/ImportCommand.php#L70-L72
> 
> I'm trying to figure out how to fix this on our side, in the meantime any help is welcome :)

This should be fixed with this https://github.com/acseo/TypesenseBundle/pull/78

**Comment by npotier** [comment]
Hello @lucasferraro thank you for your help.

This feature is merged here : https://github.com/acseo/TypesenseBundle/pull/95

I've added some doc and tests.

You can use it with version `0.7.4` of the bundle

**Comment by LauLaman** [comment]
First of all nice work! 
While trying to get this to work i encountered a small discrepancy: 

Looks like the service needs to be `public` in order to get this to work. It might be nice to have the documentation reflect this requirement

**Pull request merged**
