### PR TITLE
Use Symfony property accessor

### PR DESCRIPTION
**Pull request by pierre-H**
Allow to use more complex fields `entity_attributes` and simplify the code.
Examples: `address[0].city` or `translations[0].name`

### CODE REVIEW

**Comment by pierre-H** [comment]
@npotier
Do you plan to integrate this improvement ?

**Comment by npotier** [comment]
Hello @pierre-H thank you for this PR.

This improvement seems very cool. Give me a few time to check this before accepting it 😄

**Comment by npotier** [comment]
Merging this on `feature/sf-property-accessor` before passing it on `master`

**Comment by npotier** [comment]
Hello @pierre-H , the functionnal tests are not working right now.

I've explained the issue here : https://github.com/acseo/TypesenseBundle/pull/37

Feel free to have a look at it and tell me what you think about it.

**Comment by pierre-H** [comment]
Thank you for your feedback ! I am checking that ...

**Pull request merged**
